"""Grouped cross-validation for recursive C-band residual correction.

This checks whether the correction model survives stricter tests:
- leave-one-wavelength-out
- leave-one-span-out

It uses the recursive calibration rows generated by train_recursive_cband_correction.py.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def design_matrix(wavelength_nm: np.ndarray, spans: np.ndarray, model: str) -> np.ndarray:
    wl = np.asarray(wavelength_nm, dtype=float)
    sp = np.asarray(spans, dtype=float)

    if model == "none":
        return np.zeros((wl.size, 0))
    if model == "constant":
        return np.ones((wl.size, 1))
    if model == "wavelength_linear":
        return np.column_stack([np.ones(wl.size), wl - 1550.0])
    if model == "span_log_linear":
        return np.column_stack([np.ones(wl.size), np.log10(sp)])
    if model == "wavelength_span_linear":
        return np.column_stack([np.ones(wl.size), wl - 1550.0, np.log10(sp)])

    raise ValueError(f"Unknown model: {model}")


def fit_predict(train: pd.DataFrame, test: pd.DataFrame, model: str) -> np.ndarray:
    if model == "none":
        return np.zeros(len(test), dtype=float)

    x_train = design_matrix(
        train["wavelength_nm"].to_numpy(float),
        train["spans"].to_numpy(float),
        model,
    )
    y_train = train["recursive_raw_residual_db"].to_numpy(float)

    x_test = design_matrix(
        test["wavelength_nm"].to_numpy(float),
        test["spans"].to_numpy(float),
        model,
    )

    coef, *_ = np.linalg.lstsq(x_train, y_train, rcond=None)
    return x_test @ coef


def metric_dict(residual: np.ndarray) -> dict[str, float]:
    residual = np.asarray(residual, dtype=float)
    return {
        "n": int(residual.size),
        "rmse_db": float(np.sqrt(np.mean(residual**2))),
        "mae_db": float(np.mean(np.abs(residual))),
        "bias_db": float(np.mean(residual)),
        "max_abs_error_db": float(np.max(np.abs(residual))),
    }


def grouped_cv(frame: pd.DataFrame, group_column: str, model: str) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    all_residuals: list[float] = []

    for group_value in sorted(frame[group_column].unique()):
        train = frame[frame[group_column] != group_value].copy()
        test = frame[frame[group_column] == group_value].copy()

        predicted = fit_predict(train, test, model)
        corrected_residual = test["recursive_raw_residual_db"].to_numpy(float) - predicted

        rows.append(
            {
                "heldout_group": str(group_value),
                **metric_dict(corrected_residual),
            }
        )
        all_residuals.extend([float(x) for x in corrected_residual])

    return {
        "overall": metric_dict(np.asarray(all_residuals, dtype=float)),
        "groups": rows,
    }


def main() -> int:
    output_dir = ROOT / "releases" / "pnc-v1.0" / "results"
    input_path = output_dir / "recursive_cband_calibration_rows.csv"

    frame = pd.read_csv(input_path)
    frame["wavelength_group_nm"] = frame["wavelength_nm"].round().astype(int)
    frame["span_group"] = frame["spans"].astype(int)

    models = [
        "none",
        "constant",
        "wavelength_linear",
        "span_log_linear",
        "wavelength_span_linear",
    ]

    summary: dict[str, Any] = {
        "note": "Grouped CV on calibration rows only. Held-out rows are not used here.",
        "input_file": str(input_path),
        "rows": int(len(frame)),
        "wavelength_groups": sorted([int(x) for x in frame["wavelength_group_nm"].unique()]),
        "span_groups": sorted([int(x) for x in frame["span_group"].unique()]),
        "models": {},
    }

    for model in models:
        summary["models"][model] = {
            "leave_one_wavelength_out": grouped_cv(frame, "wavelength_group_nm", model),
            "leave_one_span_out": grouped_cv(frame, "span_group", model),
        }

    best_wavelength = min(
        models,
        key=lambda name: summary["models"][name]["leave_one_wavelength_out"]["overall"]["rmse_db"],
    )
    best_span = min(
        models,
        key=lambda name: summary["models"][name]["leave_one_span_out"]["overall"]["rmse_db"],
    )

    summary["best_model_by_leave_one_wavelength_out_rmse"] = best_wavelength
    summary["best_model_by_leave_one_span_out_rmse"] = best_span
    summary["interpretation_rule"] = (
        "Prefer a simple correction model that performs well in both grouped CV modes. "
        "If the best held-out model fails grouped CV, report recursive raw performance instead."
    )

    output_path = output_dir / "recursive_cband_grouped_cv_summary.json"
    output_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(json.dumps(summary, indent=2))
    print()
    print("Wrote:")
    print(output_path)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
